version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      no_cache: true
    container_name: chairman-app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - chairman-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  event-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    networks:
      - chairman-network

  # Redis for event queue (optional but recommended for production)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - chairman-network

networks:
  chairman-network:
    driver: bridge

volumes:
  chroma-data:
    driver: local
